spring:
  application:
    name: organization-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${CONFIGSERVER_URI:http://configserver:8071}